spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/notification
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

